name = input('Kullanıcı Adınızı Girin: 🔎 ')
age = input('Yaşınızı Girin: 🔎 ')
meslek = input('Yazılım Alanınızı Seçin: (Programlama - Web Programlama) 🔎 ')
github = input('Github Kullanıcı Adınızı Yazın: 🔎 ')
dc = input('Discord Kullanıcı Adınızı Yazın: 🔎 ')

print('---------=> 🔎PROFİLE🔎 <=---------')
print('Kullanıcı Adı: 🧫 ' + name + ' - Yaş: 📌 ' + age)
print('Mesleği: 💻 '+ meslek + ' - Tarih: 🗓️, 2024')
print('Yetkisi: 🔑 YÖNETİCİ - Banka: 💸 1M')
print('Github Kullanıcı Adi: 📃 '+ github)
print('----------🔎 LİNK🔎 ----------')
print('https://www.discord.com/'+ dc)
print('https://www.github.com/'+ github)
print('---------=>🔎 PROFİLE🔎 <=---------')